config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users
  devise_for :admins
  namespace :admin do 
    resources :users
    resources :lists
  end 
  get '/admin', to: 'admins#index'
  resources :tags, only: [:index, :show, :edit, :update, :destroy]
  resources :lists, only: [:index, :new, :create, :edit, :update, :destroy] do 
    resources :tasks do
      member do
        get :mark_as_done
      end
  
      collection do
        get :archived
      end
    end
    resources :list_accesses, only: [:new, :create]
  end
  get '/search', to: 'tasks#search'
end

app/models/list.rb
class List < ApplicationRecord
    include AlgoliaSearch
    has_many :tasks, dependent: :destroy
    has_many :tags, through: :tasks
    has_many :list_accesses, dependent: :destroy
    belongs_to :user

    validates :name, presence: true

    def update_percentage
        number_of_tasks_in_list = tasks.count
        tasks_done = tasks.select{|task| task.done == true}
        count_task = tasks_done.count
        percentage = count_task * 100 / number_of_tasks_in_list
        self.update!(percentage_done: percentage)
        if percentage == 100
            UserMailer.with(user: self.user, list: self).list_finished_email.deliver_later
        end
    end

    algoliasearch do
        attributes :name, :created_at
        searchableAttributes ['name']
        customRanking ['desc(created_at)']
    end

end

app/controllers/admin/lists_controller.rb
class Admin::ListsController < ApplicationController
    before_action :authenticate_admin!

    def show 
        @list = List.find(params[:id])
        @tasks = @list.tasks
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @lists = current_user.lists
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id

    if @list.save
      redirect_to list_tasks_path(@list), notice: 'List was successfully created.'
      List.reindex 
    else
      render :new 
    end
  end

  def update
    if @list.update(list_params)
      redirect_to list_tasks_path(@list), notice: 'List was successfully updated.' 
    else
      render :edit
    end
  end

  def destroy
    @list.destroy    
    redirect_to lists_path, notice: 'List was successfully destroyed.' 
  end

  private

  def set_list
    @list = List.find(params[:id])

    if verify_list_access == false
      redirect_to root_path, notice: "you don't have access to this list"
    end
  end

  def list_params
    params.require(:list).permit(:name, :description)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :task_description, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit :submit, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<div class="content">
    <h1 class="main_title">Your Lists</h1>
    <p class="main_title"><%= link_to 'Create a new list', new_list_path%></p>
  <br>
  <div class="container marketing">
    <div class="row">
      <% @lists.each do |list| %>
        <div class="col-lg-4">
          <div class="sub-texts">
            <%= image_tag "https://source.unsplash.com/random/" + list.name %>
            <h2><%= list.name.capitalize %></h2>
            <p><%= list.percentage_done %> % done </p>
            <p><%= list.description&.capitalize %></p>
            <p><%= link_to "View details »", list_tasks_path(list), class: "btn btn-secondary" %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <% if current_user.list_accesses.count >= 1 %>
    <h2 class="secondary_title">Lists shared with you</h2>
    <div class="container marketing">
    <div class="row">
      <% current_user.list_accesses.each do |list_access| %>
        <div class="col-lg-4">
          <div class="sub-texts">
            <svg class="bd-placeholder-img rounded-circle" width="100" height="100" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
            <h2><%= list_access.list.name.capitalize %></h2>
            <p><%= list_access.list.percentage_done%> % done </p>
            <p><%= list_access.list.description&.capitalize %></p>
            <p><%= link_to "View details »", list_tasks_path(list_access.list), class: "btn btn-secondary" %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <br>
</div>

app/views/lists/new.html.erb
<h1 class="main_title">New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>