config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users
  devise_for :admins
  namespace :admin do 
    resources :users
    resources :lists
  end 
  get '/admin', to: 'admins#index'
  resources :tags, only: [:index, :show, :edit, :update, :destroy]
  resources :lists, only: [:index, :new, :create, :edit, :update, :destroy] do 
    resources :tasks do
      member do
        get :mark_as_done
      end
  
      collection do
        get :archived
      end
    end
    resources :list_accesses, only: [:new, :create]
  end
  get '/search', to: 'tasks#search'
end

app/models/task.rb
class Task < ApplicationRecord
    include AlgoliaSearch
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    belongs_to :list

    accepts_nested_attributes_for :tags

    validates :name, presence: true
    validates :list_id, presence: true

    scope :done, -> {where done: true}

    def all_tags=(names)
      self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
      end
    end
      
    def all_tags
      self.tags.map(&:name).join(", ")
    end

    algoliasearch do
      attributes :name, :description, :created_at
      searchableAttributes ['name', 'description']
      customRanking ['desc(created_at)']
      add_attribute :user_id
    end

    def user_id
      self.list.user_id
    end
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_list, except: :search
    before_action :set_task, only: [:show, :edit, :update, :destroy, :mark_as_done]

    def index 
        @tasks = @list.tasks
        if params[:filter_by_tag] 
            @tasks = @tasks.select{|task| task.tags.any? {|tag| tag.name == params[:filter_by_tag]}} 
        end
        @tasks = @tasks.select{|task| task.done == false}
    end

    def new
        @task = Task.new
    end 

    def create
        @task = Task.new(task_params)
        @task.list_id = @list.id

        if @task.save
            @task.list.update_percentage
            redirect_to list_tasks_path(@list.id), notice: 'Task was successfully created.'
            Task.reindex
        else 
            render :new 
        end
    end 
    
    def edit 
    end 

    def update 
        if @task.update(task_params) 
            redirect_to list_tasks_path(@list.id), notice: 'Task was successfully updated.'
        else 
            render :edit 
        end
    end 

    def destroy 
        @task.destroy    
        redirect_to list_tasks_url, notice: 'Task was successfully destroyed.'
    end 

    def mark_as_done
        if @task.done
            redirect_to list_tasks_path, notice: 'This task is already done.'
        else
            @task.update!(done: true, done_at: Time.now)
            @task.list.update_percentage
            redirect_to list_tasks_path, notice: 'Congratulations, this task is done.'
        end
    end

    def archived
        @tasks = @list.tasks
        @tasks = @tasks.select{|task| task.done == true}
    end

    def search 
        @tasks = Task.search(params[:query], filters: "user_id:#{current_user.id}")
    end

    private 

    def set_list
        @list = List.find(params[:list_id])

        if verify_list_access == false
            redirect_to root_path, notice: "you don't have access to this list"
        end
    end

    def set_task
        @task = @list.tasks.find(params[:id])
    end
   
    def task_params
        params.require(:task).permit(:name, :description, :duration, :all_tags)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, url: [@list, @task], local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :task_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :duration %>
    <%= form.select :duration, [5, 10, 15, 20], id: :task_duration, class: "form-control"   %>
  </div>

  <div class="form-group">
    <%= form.label :all_tags %>
    <%= form.text_field :all_tags, placeholder: "tags here separated with a comma", class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit :submit, class: "btn btn-secondary" %>
  </div>
  <br>
<% end %>

app/views/tasks/_index.html.erb
<p class="main_title"><%= link_to 'New Task', new_list_task_path, class: "secondary-pages-links" %>
<br>
<%= link_to 'Give list access to a friend', new_list_list_access_path(@list), class: "secondary-pages-links" %>
<br>
<%= link_to 'Delete list', list_path(@list), method: :delete, data: { confirm: 'Are you sure?' }, class: "secondary-pages-links" %></p>


<% if params[:filter_by_tag] %>
  <%= link_to list_tasks_path(@list) do %> 
    <span class="badge badge-secondary"> clear filter </span>
  <% end %>
<% end %>
<div class="my-3 p-3 bg-white rounded box-shadow">
  <h6 class="border-bottom border-gray pb-2 mb-0"><%= @list.name %></h6> 
  <% if @tasks.size == 0 %>
    <p>No tasks in this list</p>
  <% end %>
  
  <% @tasks.each do |task| %>
    <div class="media text-muted pt-3">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark"><%= "#{task.name.capitalize}, #{task.duration}" %> mins</strong>
        <%= task.description %>
        tags: 
        <% task.tags.each do |tag| %>
          <%= link_to list_tasks_path(@list, filter_by_tag: tag.name) do %> 
            <span class="badge badge-secondary"> <%= tag.name %> </span>
          <% end %>
        <% end %>
        created on: <%= task.created_at.strftime("%b %d at %I:%M %p") %>
        <% if task.done %>
          done on: <%= task.done_at.strftime("%b %d at %I:%M %p") %>
        <% else %>
          <%= link_to 'Mark as done', mark_as_done_list_task_path(@list, task), class: "secondary-pages-links " %>
        <% end %>
        <%= link_to 'Edit', edit_list_task_path(@list, task), class: "secondary-pages-links" %>
        <%= link_to 'Destroy', list_task_path(@list, task), method: :delete, data: { confirm: 'Are you sure?' }, class: "secondary-pages-links" %>
      </p>
    </div>
  <% end %>
</div>
  <small class="d-block text-right mt-3">
    <%= link_to 'Back', lists_path, class: "secondary-pages-lower-texts" %>
  </small>
</div>

app/views/tasks/archived.html.erb
<div class="main_title">
    <h1>Archived Tasks</h1>
</div> 
<%= render 'index' %> 
<small class="d-block text-right mt-3">
    <%= link_to 'Active Tasks', list_tasks_path, class: "secondary-pages-lower-texts" %>
</small>

app/views/tasks/edit.html.erb
<div class="main_title">
  <h1>Editing task</h1>
</div> 
<%= render 'form', task: @task %>

<%= link_to 'Back', list_tasks_path %>

app/views/tasks/index.html.erb
<div class="main_title">
  <h1>Tasks</h1>
</div> 
<%= render 'index' %>
<small class="d-block text-right mt-3">
  <%= link_to 'Archived tasks', archived_list_tasks_path, class: "secondary-pages-lower-texts" %>
</small>

app/views/tasks/new.html.erb
<div class="main_title">
  <h1>New Task</h1>
</div> 

<%= render 'form', task: @task %>

<%= link_to 'Back', list_tasks_path %>

app/views/tasks/search.html.erb
<div class="my-3 p-3 bg-white rounded box-shadow">
  <h6 class="border-bottom border-gray pb-2 mb-0">Tasks corresponding:</h6> 
  <% if @tasks.size == 0 %>
    <p>No tasks corresponding to your search</p>
  <% end %>
  
  <% @tasks.each do |task| %>
    <div class="media text-muted pt-3">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark"><%= task.name.capitalize %></strong>  
        in the list: <%= link_to task.list.name, list_tasks_path(task.list_id) %>
      </p>
    </div>
  <% end %>
</div>
  <small class="d-block text-right mt-3">
    <%= link_to 'Home', root_path, class: "secondary-pages-lower-texts" %>
  </small>
</div>