config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users
  devise_for :admins
  namespace :admin do 
    resources :users
    resources :lists
  end 
  get '/admin', to: 'admins#index'
  resources :tags, only: [:index, :show, :edit, :update, :destroy]
  resources :lists, only: [:index, :new, :create, :edit, :update, :destroy] do 
    resources :tasks do
      member do
        get :mark_as_done
      end
  
      collection do
        get :archived
      end
    end
    resources :list_accesses, only: [:new, :create]
  end
  get '/search', to: 'tasks#search'
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :tasks, through: :taggings

    accepts_nested_attributes_for :tasks
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :set_tag, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    
    def index 
        @tags = current_user.tags
    end

    def show
    end
    
    def edit 
    end 

    def update 
        if @tag.update(tag_params) 
            redirect_to @tag, notice: 'Tag was successfully updated.'
        else 
            render :edit
        end
    end 

    def destroy 
        @tag.destroy
        redirect_to tags_url, notice: 'Tag was successfully destroyed.'
    end 

    private 

    def set_tag
        @tag = Tag.find(params[:id])
    end

    def tag_params
        params.require(:tag).permit(:name, :all_tags)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tag_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%=tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'Home', root_path %></p>
<p><%= link_to 'Logout', destroy_user_session_path, method: :delete %></p>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>