config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users
  devise_for :admins
  namespace :admin do 
    resources :users
    resources :lists
  end 
  get '/admin', to: 'admins#index'
  resources :tags, only: [:index, :show, :edit, :update, :destroy]
  resources :lists, only: [:index, :new, :create, :edit, :update, :destroy] do 
    resources :tasks do
      member do
        get :mark_as_done
      end
  
      collection do
        get :archived
      end
    end
    resources :list_accesses, only: [:new, :create]
  end
  get '/search', to: 'tasks#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy
  has_many :tags, through: :lists
  has_many :list_accesses, dependent: :destroy

  validates :name, presence: true
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!

    def index 
        @users = User.all
    end 

    def show
        @user = User.find(params[:id])
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_users_path, notice: "User deleted"
    end 
end 

app/views/admin/users/index.html.erb
<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.email, admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', admin_path %>

app/views/admin/users/show.html.erb
<h1>User infos</h1>
<h2>lists</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.lists.each do |list| %>
      <tr>
        <td><%= link_to list.name, admin_list_path(list) %></td>
        <td><%= list.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', admin_users_path %>